#!/usr/bin/env python3
from pathlib import Path
import json,re,unicodedata,collections
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; DATA.mkdir(parents=True,exist_ok=True)

def D(i,n,l,f,m,h,s,se,st,c,b): return {'id':i,'name':n,'locations':l,'families':f,'materials':m,'hazards':h,'secrets':s,'sensory':se,'stakes':st,'characters':c,'bosses':b}
DOMAINS=[
D('mata_fio_verde','Mata do Fio Verde',['Catedral de Samaúma','Casa dos Mapas de Casca','Poço de Seiva Negra','Trilha que Retorna','Ponte de Cipós','Jardim dos Nomes','Ruínas de Iramã','Covil do Cerne Faminto','Clareira dos Juramentos','Árvore-Nó de Aru'],['Cães de Casca','Onças de Casca','Aranhas de Nó','Macacos de Liana','Vespas de Seiva','Cervos de Musgo','Fungos Caminhantes','Predadores de Raiz'],['seiva negra','casca viva','raízes antigas','cipós tensos','musgo luminoso'],['raízes que fecham caminhos','esporos que confundem direção','predadores de casca','juramentos presos à madeira'],['um mapa cresce conforme a confiança muda','uma promessa esquecida sustenta a passagem','a seiva vem de algo que não é árvore','nomes podem ser cultivados'],['cheiro de terra molhada','estalidos de madeira sob tensão','luz verde filtrada','gosto metálico de seiva'],['preservar uma rota','honrar uma promessa','salvar um viajante','não destruir um registro vivo'],['Rastreador de Nós','Guardião de Casca','Cantora de Cipós'],['Cerne Faminto','Samaúma Juramentada','Cartógrafo Enraizado','Rainha dos Nomes','Guardião da Árvore-Nó']),
D('varzea_espelhos','Várzea dos Espelhos',['Foz Invertida','Lago das Duas Luas','Casa sobre Estacas Vazias','Ilha que Repete','Espelho Fundo','Canal das Vozes Gêmeas','Porto de Água Parada','Mangue dos Rostos','Aldeia da Maré Reversa','Poço do Céu Afogado'],['Reflexos Famintos','Jacarés de Espelho','Enguias de Duplo Corpo','Garças Invertidas','Cardumes de Memória','Lodos Reflexivos','Anfíbios de Prata','Afogados sem Rosto'],['água prateada','estacas sem fundo','lodo espelhado','juncos de duas sombras'],['correntes invertidas','reflexos que agem antes do corpo','ilhas que repetem trajetos','afogados sem rosto'],['objetos chegam antes de serem perdidos','uma segunda lua só existe no reflexo','a casa se apoia em outra versão do terreno','alguns reflexos lembram escolhas recusadas'],['cheiro de chuva parada','água fria nos tornozelos','reflexos tremendo sem vento','cantos duplicados de aves'],['decidir qual versão acreditar','manter uma comunidade acima da cheia','impedir que um reflexo substitua alguém','usar uma maré impossível'],['Barqueiro do Reflexo','Pescadora de Presságios','Afogado Retornado'],['Rei do Reflexo Fundo','Matriarca das Duas Luas','Casa que Caminha','Afogado sem Primeiro Rosto','Maré que Volta']),
D('costa_sinos_afogados','Costa dos Sinos Afogados',['Cidade Submersa de Odria','Farol dos Destinos','Baía do Eco Tardio','Quebra-Mar dos Mortos','Fossa de Nácar Negro','Campanário Naufragado','Praia dos Salvados Impossíveis','Recife das Correntes','Porto das Sete Marés','Cemitério de Âncoras'],['Cavaleiros de Coral','Gaivotas de Tempestade','Caranguejos de Bronze','Enguias de Sino','Afogados de Odria','Medusas de Nácar','Lobos de Espuma','Leviatãs Menores'],['bronze salgado','coral negro','cordas encharcadas','nácar frio'],['tempestades que repetem vozes','sinos que atraem correntes','ruas que afundam com a maré','salvados de versões inexistentes'],['o farol ilumina destinos','uma badalada desapareceu na noite da Ruptura','sons chegam antes de sua causa','Odria possui mais de uma história'],['sal nos lábios','bronze vibrando sob os pés','espuma fria','vento cheio de vozes'],['salvar um porto','escolher uma rota futura','preservar um naufrágio histórico','decidir quem controla uma corrente'],['Sineiro Náufrago','Corsária de Coral','Vigia de Maré'],['Matriarca dos Sinos de Coral','Almirante de Odria Afogada','Tempestade de Asas','Capitão Calcificado','Leviatã Sincrônico']),
D('chapada_sol_oco','Chapada do Sol Oco',['Cratera do Sol Oco','Cidade das Sete Sombras','Cisterna de Jaru','Vila sem Noite','Poço de Meio-Dia','Obelisco da Oitava Sombra','Santuário do Eclipse','Campo do Vidro Solar','Observatório das Horas Mortas','Estrada do Sol Partido'],['Homens de Sol','Escorpiões de Sombra','Lagartos de Vidro','Abutres de Meio-Dia','Serpentes de Calor','Cabras do Eclipse','Besouros de Obelisco','Miras de Luz'],['vidro solar','pedra alaranjada','tecido de sombra','bronze aquecido'],['calor que altera memória','sombras que não obedecem seus donos','espelhos que roubam a noite','escorpiões de sombra'],['a oitava sombra não consta dos calendários','os obeliscos sustentam privilégios antigos','o Sol Oco já teve outra trajetória','alguns bairros compram sombra de outros'],['ar seco cortando a garganta','pedra quente nas botas','luz branca sem conforto','vento cheirando a poeira'],['redistribuir água','decidir quem recebe sombra','corrigir um calendário injusto','preservar a noite'],['Lanceiro Solar','Caminhante de Sombra','Oráculo do Meio-Dia'],['Matilha do Meio-Dia','Observatório Vivo','Escorpião da Sombra Única','Homem sem Sombra','Coração do Sol Oco']),
D('salinas_ossamar','Salinas de Ossamar',['Costelas do Leviatã','Poço das Sete Cordas','Miragem Azul','Ventre de Ossamar','Olho do Mar Ausente','Santuário da Última Gota','Ossuário das Marés','Mercado do Sal Vivo','Dunas de Concha','Baía sem Água'],['Fósseis Andantes','Lagartos de Sal','Abutres de Osso','Escorpiões Calcificados','Peixes de Areia','Vermes de Concha','Carneiros de Salmoura','Sirenes Secas'],['sal vivo','osso fossilizado','cordas de poço','conchas secas'],['sede extrema','fósseis que despertam','miragens com peso','tempestades de sal'],['o oceano talvez ainda pressione o mundo','objetos molhados surgem no deserto','fósseis guardam inscrições','uma gota nunca cai'],['sal queimando a pele','vento seco assobiando em costelas','cheiro impossível de maresia','claridade branca ofuscante'],['partilhar água','preservar um arquivo fóssil','seguir uma miragem verdadeira','decidir se o mar deve retornar'],['Catador de Ossos','Peregrina da Sede','Paleocaçador'],['Leviatã de Sal','Guardião das Sete Cordas','Miragem que Bebe','Ossário Andante','Olho do Mar Ausente']),
D('vertice','Vértice',['Cidade Suspensa de Avar','Elevador de Contrapeso','Mercado dos Cabos','Ponte sem Pilar','Observatório do Abismo','Mosteiro do Vento','Ninho das Serpes','Bairro das Âncoras','Torre de Tensão','Plataforma sem Sombra'],['Serpes de Nuvem','Corvos de Cabo','Cabras de Penhasco','Aranhas de Ponte','Mantos de Vento','Golems de Contrapeso','Morcegos de Abismo','Falcões de Tensão'],['cabos trançados','pedra suspensa','contrapesos de ferro','tecido de vento'],['quedas sem fundo','rajadas laterais','pontes sob tensão','cargas mal distribuídas'],['algumas estruturas são sustentadas por promessas','o abismo contém uma cidade','uma ponte projeta pilar que não existe','o vento repete cálculos'],['vento rasgando o ouvido','cordas vibrando como instrumentos','névoa abaixo dos pés','metal frio nas mãos'],['redistribuir peso','salvar uma ponte','decidir quem pode construir','manter uma promessa estrutural'],['Duelista do Abismo','Engenheira de Pontes','Monge do Vento'],['Serpe das Mil Pontes','Mestre dos Contrapesos','Vento com Nome','Abismo que Responde','Ponte Juramentada']),
D('forja_rubra','Forja Rubra',['Forja Central','Bairro dos Moldes','Rio de Escória','Torre de Têmpera','Pátio dos Inacabados','Mina do Ferro Vivo','Galeria dos Martelos','Câmara do Primeiro Fogo','Ponte da Caldeira','Arquivo de Matrizes'],['Soldados Inacabados','Cães de Escória','Autômatos de Martelo','Vermes de Fornalha','Tecelões de Arame','Gárgulas de Ferro','Enxames de Rebite','Moldes Vivos'],['ferro vivo','escória quente','matrizes de bronze','rebites incandescentes'],['caldeiras autônomas','máquinas obedecendo ordens mortas','metal que se defende','linhas de produção sem mestre'],['uma máquina aponta para o Tear','ordens vêm de pessoas mortas','peças descartadas retornam melhores','o Primeiro Fogo lembra quem o acendeu'],['calor de fornalha','gosto de fuligem','martelos ritmados','óleo queimado'],['dar direitos aos Inacabados','desligar uma fábrica','concluir uma máquina','controlar o Primeiro Fogo'],['Ferreiro de Guerra','Desertor da Forja','Tecelã de Metal'],['Mestre-Matriz Zero','Caldeira que Sonha','General Inacabado','Sindicato dos Mil Martelos','Primeiro Fogo']),
D('mar_cinza','Mar de Cinza',['Cemitério de Marcas','Dunas sem Nome','Mosteiro da Última Memória','Estrada Apagada','Poço de Fuligem','Bosque Carbonizado','Mercado dos Nomes','Farol Cinzento','Ruínas de Ninguém','Boca do Esquecimento'],['Devoradores de Marca','Lobos de Fuligem','Monges Vazios','Nomes Perdidos','Corvos de Cinza','Vultos Apagados','Cervos sem Rastro','Erasores'],['cinza fina','pedra sem nome','fuligem fria','papel queimado'],['esquecimento progressivo','nomes negociados','marcas apagadas','estradas que somem da lembrança'],['algo esquecido pode continuar causando efeitos','nomes carregam dívidas','a Cinza preserva algumas verdades ao apagá-las de todos','a Boca devolve histórias modificadas'],['silêncio abafado','cinza nos dentes','frio sem vento','cheiro de papel queimado'],['decidir o que merece ser lembrado','assumir um nome alheio','preservar uma culpa','impedir uma guerra sem apagar a verdade'],['Penitente Cinzento','Necrógrafa','Sem-Nome'],['Rei sem Nome','Abadessa da Última Memória','Farol que Esquece','Cidade Ninguém','Boca do Esquecimento']),
D('noite_iscara','Noite de Iscara',['Palácio sob o Gelo','Campo das Auroras Baixas','Fogueira de Orun','Lago dos Futuros','Vila do Sol Ausente','Geleira dos Sussurros','Observatório Boreal','Floresta de Cristal','Estrada da Brasa','Poço da Noite'],['Lobos de Vidro','Ursos de Aurora','Cervos de Gelo','Corujas do Futuro','Serpentes de Brasa','Espectros Boreais','Caribus de Cristal','Caçadores de Neve'],['gelo azul','brasa branca','cristal de aurora','pele de neve'],['frio que cristaliza pensamentos','futuros vazando em sonhos','auroras que alteram rotas','predadores de vidro'],['algumas memórias ainda não aconteceram','o Sol Ausente pode ser uma escolha','a aurora registra futuros descartados','uma fogueira queima lembranças em vez de lenha'],['ar que dói nos pulmões','gelo rangendo','aurora sem som','fumaça doce de brasa'],['manter uma fogueira','escolher qual futuro avisar','salvar alguém de uma memória futura','decidir se a noite deve terminar'],['Caçadora de Aurora','Portador da Brasa','Sonhador de Gelo'],['Urso do Futuro Partido','Rainha da Aurora Baixa','Fogueira que Recorda','Palácio sob o Gelo','Noite sem Amanhã']),
D('cidade_mil_portas','Cidade das Mil Portas',['Porta Zero','Praça das Chaves','Tribunal do Limiar','Corredor de Contrabando','Arquivo Topológico','Estação das Doze Soleiras','Mercado dos Destinos','Bairro sem Endereço','Torre das Fechaduras','Pátio das Portas Mortas'],['Mímicos de Porta','Cães de Soleira','Chaveiros Vazios','Aranhas de Fechadura','Guardas de Limiar','Ratos de Corredor','Sombras de Endereço','Portas Famintas'],['latão de chave','madeira de soleira','pedra topológica','tinta de endereço'],['portas que trocam destino','corredores que se reescrevem','mímicos de passagem','leis incompatíveis entre bairros'],['Porta Zero abre para lugares sem coordenada','algumas chaves são relações e não objetos','um endereço pode ser roubado','a cidade possui mais portas do que paredes'],['eco de fechaduras','latão frio','passos vindo de corredores inexistentes','cheiro de madeira encerada'],['controlar acesso','libertar uma passagem','julgar quem possui uma chave','impedir monopólio de rotas'],['Chaveiro','Contrabandista de Portas','Magistrada do Limiar'],['Juiz da Porta Zero','Chave que Escolhe Dono','Bairro sem Endereço','Mímico das Doze Soleiras','Cidade que Fecha']),
D('arquivo_ecos','Arquivo dos Ecos',['Galeria das Mortes','Sala dos Índices Vivos','Biblioteca das Vozes','Poço de Tinta','Arquivo das Jornadas','Corredor das Rasuras','Salão dos Copistas','Câmara dos Nomes Mortos','Estante sem Fim','Pátio dos Ecos Órfãos'],['Rasuras','Copistas Vazios','Bibliotecários Mortos','Ecos Predatórios','Índices Vivos','Manchas de Tinta','Folhas Cortantes','Memórias Órfãs'],['tinta viva','papel de memória','couro de códice','vidro de índice'],['rasuras predatórias','memórias órfãs','textos que reescrevem leitores','ecos que exigem autoria'],['algumas páginas lembram jornadas que nunca ocorreram','um índice pode apagar alguém','a Galeria registra mortes alternativas','o Arquivo talvez tenha provocado a Poda'],['cheiro de tinta fresca','sussurro de páginas','pó frio de estante','pena riscando sozinha'],['preservar uma memória','decidir quem pode editar um registro','libertar um Eco','não confundir lembrança com verdade'],['Arquivista','Repetente','Curadora de Ecos'],['Rasura-Mãe','Bibliotecário das Mortes','Índice que Lê Pessoas','Memória sem Autor','Arquivo que se Defende']),
D('tear_desfeito','Tear Desfeito',['Nó Original','Cidade de Fragmentos','Oficina das Causas','Campo dos Futuros Abortados','Ponte para Ontem','Jardim das Versões','Fenda das Regras','Trono da Convergência','Último Fio','Sala sem Causa'],['Futuros Abortados','Nós Famintos','Tecelões Invertidos','Bestas de Possibilidade','Fragmentos Humanos','Rupturas Ambulantes','Paradoxos Menores','Formas sem Causa'],['fio causal','pedra impossível','vidro de futuro','nós de luz opaca'],['regras locais falhando','causas chegando depois dos efeitos','futuros abortados','paradoxos famintos'],['o Nó Original não é necessariamente o primeiro','a Ruptura pode ter sido contenção','algumas versões do mundo recusam convergir','o Tear responde a Marcas de jornadas anteriores'],['som chegando atrasado','linhas vibrando no ar','peso mudando sem movimento','luz com sombra invertida'],['escolher o que deve convergir','recusar um centro','reatar sem criar tirania','aceitar múltiplos futuros'],['Tecelão Fraturado','Herdeira do Nó','Inacabado'],['Futuro que Recusou Morrer','Nó Faminto Original','Tecelão Invertido','Trono da Convergência','Último Fio'])]
FIRST=['Aru','Maela','Tori','Jaciara','Iri','Kael','Nilo','Sara','Lume','Araci','Téo','Tainá','Orun','Mira','Savel','Ciro','Lira','Dara','Eron','Vela','Noa','Tess','Ivo','Mara','Rian']
ROLES=['cartógrafo','curandeira','guarda','mercador','barqueiro','artesã','caçador','eremita','mensageira','arquivista','ferreiro','vigia','guia','juíza','contrabandista','colecionador','peregrina','mecânico','oráculo','cozinheira','tecelão','músico','mineira','escriba','mediador']
VOICES=['mede cada palavra','usa comparações concretas','ri quando está nervoso','faz perguntas antes de responder','fala baixo e nunca repete uma frase','corrige os próprios detalhes','transforma tudo em histórias alheias','prefere pesos e distâncias','fala com solenidade','usa humor seco','não promete sem dizer o preço','evita nomes próprios','fala rápido diante de contradições','deixa longos silêncios','cita e contesta provérbios','responde com precisão desconfortável','parece casual quando esconde algo','fala como num depoimento','usa o ambiente como metáfora','muda para o plural ao falar de culpa','evita dizer eu','usa palavras arcaicas','tem voz calorosa e decisões duras','se irrita com imprecisão','fala do futuro como lembrança']
RES=['Tensão','Seiva','Acorde','Reflexo','Presságio','Fôlego Afogado','Ressonância','Saque','Maré','Calor','Sombra','Claridade','Ossos','Sede','Vestígio','Impulso','Tensão de Cabo','Sopro','Calor da Forja','Deserção','Trama Metálica','Cinza','Epitáfio','Ausência','Brilho','Brasa','Sonho','Chave','Atalho','Jurisdição','Memória','Eco','Remendo','Fratura','Herança','Mutação']
MODS=['Jovem','Ancião','Errante','Pálido','Fendido','Veloz','Couraçado','Silencioso','Faminto','Ressonante','Cego','Vermelho','Oco','Vigilante','Solitário','Deformado','Marcado','Trepador','Submerso','Crepuscular','Cintilante','Enraizado','Migrante','Guardião','Predador']
FORMS=['Lâmina','Adaga','Machado','Lança','Arco','Broquel','Elmo','Couraça','Botas','Manto','Anel','Amuleto','Frasco','Erva','Pergaminho','Chave','Martelo','Corda','Lanterna','Moeda','Cristal','Ração','Relíquia','Ferramenta','Faca','Escudo','Capuz','Colete','Sandálias','Talismã','Unguento']
VIS=['short_sword','dagger','axe','spear','bow','shield','helmet','chest_armor','boots','cloak','ring','amulet','bottle','herb','scroll','key','hammer','rope','lantern','coin','crystal','food_pouch','relic','hammer','dagger','shield','helmet','chest_armor','boots','amulet','bottle']
FRAMES=[('exploration','Um detalhe fora do lugar obriga você a ler o ambiente antes de avançar.'),('resource','Há algo útil aqui, mas retirá-lo muda o equilíbrio do lugar.'),('social','Duas pessoas contam versões incompatíveis do mesmo acontecimento.'),('hazard','O perigo não ataca de imediato; ele piora a cada hesitação.'),('creature','Uma criatura ferida ocupa o caminho e talvez esteja fugindo de algo pior.'),('choice','Uma solução rápida transfere o custo para alguém que não está presente.'),('knowledge','Uma inscrição contradiz tudo o que se dizia sobre este lugar.'),('mark','Sua decisão anterior é reconhecida por alguém ou por alguma coisa.'),('debt','Uma promessa antiga cobra retorno em momento inconveniente.'),('trade','Um comerciante aceita um pagamento que não é dinheiro.'),('route','Duas Veredas parecem levar ao mesmo destino, mas exigem perdas diferentes.'),('ritual','Um procedimento local funciona, embora ninguém concorde sobre o motivo.'),('weather','O ambiente muda de modo previsível apenas para quem observou detalhes anteriores.'),('faction','Duas facções disputam controle sem que nenhuma consiga operar o lugar sozinha.'),('memory','Você encontra prova de uma versão de si mesmo que não viveu esta jornada.'),('moral','A alternativa mais segura é também a que apaga uma verdade importante.'),('callback','Algo que você fez várias Batidas atrás finalmente alcança você.')]
A=['Examinar','Preservar','Ouvir','Esperar','Ajudar','Assumir','Ler','Reconhecer','Cumprir','Negociar','Comparar','Executar','Observar','Mediar','Confrontar','Proteger','Responder']; B=['Intervir','Extrair','Questionar','Atravessar','Seguir','Transferir','Copiar','Negar','Adiar','Recusar','Arriscar','Improvisar','Forçar','Favorecer','Apagar','Ocultar','Romper']; C=['Contornar','Partilhar','Registrar','Recuar','Libertar','Revelar','Guardar','Aceitar','Pagar','Trocar','Marcar','Interromper','Aguardar','Dividir','Ancorar','Confessar','Desfazer']

def emit(name,rows): (DATA/f'{name}.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8')
def gen():
 r=collections.defaultdict(list); ci=0
 for d in DOMAINS:
  x=d['id']; r['worlds'].append({'id':f'world.{x}','name':d['name'],'domain_id':x,'locations':[f'location.{x}.{i+1:02d}' for i in range(10)]})
  for i,n in enumerate(d['locations']): r['locations'].append({'id':f'location.{x}.{i+1:02d}','world_id':f'world.{x}','name':n,'premise':f"{n} é marcado por {d['materials'][i%len(d['materials'])]} e por {d['hazards'][i%4]}.",'secret':d['secrets'][i%4],'conflict':d['stakes'][i%4],'sensory':d['sensory'][i%4]})
  for i,n in enumerate(d['families']): r['families'].append({'id':f'family.{x}.{i+1:02d}','world_id':f'world.{x}','name':n,'role':['predator','controller','skirmisher','tank','swarm','artillery','attrition','trickster'][i]})
  for i in range(25):
   f=d['families'][i%8]; name=f"{f[:-1] if f.endswith('s') else f} {MODS[i]}"; mech=['distance_pressure','status_combo','posture_break','defense_cycle','multi_attack','telegraphed_range','resource_drain','intent_trick'][i%8]
   r['monsters'].append({'id':f'monster.{x}.{i+1:02d}','world_id':f'world.{x}','location_id':f'location.{x}.{i%10+1:02d}','family_id':f'family.{x}.{i%8+1:02d}','name':name,'hp':10+(i%6)*3+(i//8)*2,'posture':6+(i%5)*2,'mechanic':mech,'ecology':f"{name} ocupa {d['locations'][i%10].lower()}, onde {d['materials'][i%len(d['materials'])]} oferece abrigo; compete em torno de {d['stakes'][i%4]} e evita {d['hazards'][(i+2)%4]}.",'counterplay':f"A janela surge quando {d['sensory'][i%4]} anuncia mudança de comportamento; explore {['ritmo','alcance','postura','estado','terreno'][i%5]} ({i+1}/25).",'intent_signature':f'{x}:{mech}:{i+1:02d}'})
  for i,n in enumerate(d['bosses']): r['bosses'].append({'id':f'boss.{x}.{i+1:02d}','world_id':f'world.{x}','location_id':f'location.{x}.{(i*2)%10+1:02d}','name':n,'conflict':f"Decidir como {d['stakes'][i%4]} sem ignorar que {d['secrets'][i%4]}.",'phases':[{'threshold':1.0,'name':'Leitura'},{'threshold':.6,'name':'Ruptura'},{'threshold':.25,'name':'Consequência'}]})
  for i in range(93): r['items'].append({'id':f'item.{x}.{i+1:03d}','world_id':f'world.{x}','name':f"{FORMS[i%31]} de {d['materials'][(i*3+i//7)%len(d['materials'])].title()} {['do Juramento','da Vigília','do Retorno'][i//31]}",'kind':['equipment','equipment','equipment','consumable','tool','component'][i%6],'visual_archetype':VIS[i%31],'rarity':['common','uncommon','rare','singular','relic','echo'][min(5,i//16)],'effect':{'op':['damage','posture','guard','heal','vigor','range','status_power','status_resist','load','resource_gain','debt_pressure','mark_synergy'][i%12],'value':1+i%5},'description':f"Carrega sinais de {d['sensory'][i%4]} e foi adaptado para {d['stakes'][i%4]}."})
  for i in range(25):
   nm=f"{FIRST[i]} de {d['locations'][i%10]}"; r['npcs'].append({'id':f'npc.{x}.{i+1:02d}','world_id':f'world.{x}','location_id':f'location.{x}.{i%10+1:02d}','name':nm,'role':ROLES[(i+ci)%25],'objective':f"{nm} quer {d['stakes'][i%4]} antes que {d['hazards'][(i+1)%4]} torne o lugar inviável.",'pressure':f"Sabe que {d['secrets'][(i+2)%4]} e teme perder {d['materials'][(i+3)%len(d['materials'])]} se falar.",'voice':f"{VOICES[(i+ci)%25]}; menciona {d['sensory'][(i+ci)%4]}."})
  for i in range(17): r['marks'].append({'id':f'mark.{x}.{i+1:02d}','world_id':f'world.{x}','name':f"{['Rastro','Vínculo','Segredo','Cicatriz','Mudança','Eco'][i%6]} de {d['locations'][i%10]}",'type':['action','bond','knowledge','condition','world','echo'][i%6],'intensity_max':5})
  for i in range(10): r['debts'].append({'id':f'debt.{x}.{i+1:02d}','world_id':f'world.{x}','origin_location_id':f'location.{x}.{i+1:02d}','soft_deadline':4+i%3,'hard_deadline':9+i%4,'pressure_growth':.18+(i%4)*.04})
  for j,n in enumerate(d['characters']):
   cid=f'character.{x}.{j+1:02d}'; resource=RES[ci]; aids=[]
   for k in range(2):
    aid=f'ability.{x}.{j+1:02d}.{k+1}'; aids.append(aid); mech=['damage','posture','guard','heal','move','status','counter','resource','echo','mark','debt','range'][(ci*2+k)%12]; r['abilities'].append({'id':aid,'character_id':cid,'name':f"{['Cortar','Ancorar','Ouvir','Fisgar','Dobrar','Ressoar'][ci%6]} {d['materials'][(j+k)%len(d['materials'])].title()}",'resource':resource,'cost':2+k,'mechanic':mech,'signature':f'{mech}:{(ci+k)%3}:{1+(ci+k)%5}:{(ci*7+k)%11}'})
   r['characters'].append({'id':cid,'world_id':f'world.{x}','name':n,'resource':resource,'resource_max':5+ci%3,'passive':f"{n} converte {d['sensory'][j%4]} em {resource.lower()} quando muda a forma de lidar com {d['stakes'][j%4]}.",'weakness':f"{n} perde eficiência quando insiste duas vezes contra {d['hazards'][j%4]}.",'abilities':aids,'personal_question':f"Até onde aceita {d['stakes'][(j+1)%4]} quando descobre que {d['secrets'][(j+2)%4]}?"}); ci+=1
  for li,loc in enumerate(d['locations']):
   for fi,(typ,lead) in enumerate(FRAMES):
    mat=d['materials'][(li+fi)%len(d['materials'])]; haz=d['hazards'][(li*2+fi)%4]; sec=d['secrets'][(li+fi*3)%4]; sen=d['sensory'][(li+fi)%4]; stake=d['stakes'][(li+fi)%4]
    r['events'].append({'id':f'event.{x}.loc{li+1:02d}.{fi+1:02d}','world_id':f'world.{x}','location_id':f'location.{x}.{li+1:02d}','pool':typ,'title':f'{loc} — {typ.title()}','text':f'{lead} Em {loc}, {sen}; {mat} mostra sinais de que {haz}. O detalhe decisivo: {sec}. Você terá de escolher como {stake}.','choices':[{'text':f'{A[fi]} {mat} antes de decidir','effect':{'op':'mark_add','mark_id':f'mark.{x}.{fi%17+1:02d}','intensity':1}},{'text':f'{B[fi]} apesar de {haz}','effect':{'op':'resource_add','resource':'vigor','value':-1-fi%2}},{'text':f'{C[fi]} e aceitar que {stake} ficará para depois','effect':{'op':'flag_set','key':f'{x}_{li}_{fi}_deferred','value':True}}],'weight':1+((li*17+fi)%7)*.08,'cooldown_turns':4+fi%5,'max_per_run':1})
  for ai in range(17): r['events'].append({'id':f'event.{x}.arc.{ai+1:02d}','world_id':f'world.{x}','location_id':f'location.{x}.{ai%10+1:02d}','pool':'arc','title':f"{d['name']}: Fio {ai+1}",'text':f"{d['materials'][ai%len(d['materials'])]} revela que {d['secrets'][ai%4]}. Isso torna impossível tratar {d['stakes'][ai%4]} como problema local.",'choices':[{'text':'Registrar a evidência','effect':{'op':'mark_add','mark_id':f'mark.{x}.{ai+1:02d}','intensity':1}},{'text':'Compartilhar a descoberta','effect':{'op':'flag_set','key':f'arc_{x}_{ai}_shared','value':True}},{'text':'Ocultar por enquanto','effect':{'op':'resource_add','resource':'essence','value':1}}],'weight':.55,'max_per_run':1})
  for i in range(3): r['finals'].append({'id':f'ending.{x}.{i+1:02d}','world_id':f'world.{x}','name':f"{['Reatar','Liberar','Recusar'][i]} — {d['name']}",'state_signature':f"{x}:{['stabilized','distributed','open'][i]}:{i}",'epilogue':f"A solução escolhe {d['stakes'][i%4]} sabendo que {d['secrets'][i%4]}."})
  for pn in ['exploration','social','hazard','creature','knowledge','trade','route','ritual','faction','memory','callback','arc']: r['pools'].append({'id':f'pool.{x}.{pn}','world_id':f'world.{x}','name':pn})
 for ch in r['characters']:
  x=ch['world_id'].split('.',1)[1]; d=next(q for q in DOMAINS if q['id']==x)
  for st in range(8): r['events'].append({'id':f"event.personal.{ch['id'].split('.',1)[1]}.{st+1:02d}",'world_id':ch['world_id'],'location_id':f'location.{x}.{st%10+1:02d}','character_id':ch['id'],'pool':'personal_story','title':f"{ch['name']} — Capítulo {st+1}",'text':f"{ch['name']} confronta {d['secrets'][st%4]} enquanto {d['sensory'][st%4]} torna sua pergunta pessoal impossível de evitar: {ch['personal_question']}",'choices':[{'text':f"Assumir que {d['stakes'][st%4]} também é sua responsabilidade",'effect':{'op':'flag_set','key':f'personal_{st}_assume','value':True}},{'text':f"Rejeitar que {d['secrets'][st%4]} defina seu caminho",'effect':{'op':'mark_add','mark_id':f'mark.{x}.{(st+8)%17+1:02d}','intensity':1}},{'text':'Procurar outra testemunha','effect':{'op':'flag_set','key':f'personal_{st}_open','value':True}}]})
 for d in DOMAINS: r['events'].append({'id':f"event.{d['id']}.transit_consequence",'world_id':f"world.{d['id']}",'pool':'transit_callback','title':f"Consequência em trânsito — {d['name']}",'text':f"Uma consequência atravessa a Vereda. O que começou como tentativa de {d['stakes'][0]} agora carrega sinais de que {d['secrets'][1]}.",'choices':[{'text':'Enfrentar agora','effect':{'op':'debt_resolve_oldest','world_id':f"world.{d['id']}"}},{'text':'Adiar pagando Essência','effect':{'op':'resource_add','resource':'essence','value':-1}},{'text':'Transformar em Marca','effect':{'op':'mark_add','mark_id':f"mark.{d['id']}.17",'intensity':1}}]})
 for k,v in r.items(): emit(k,v)
 print('generated',sum(len(v) for v in r.values()),'records')
if __name__=='__main__': gen()
